FROM python:3.10.9-alpine3.17
COPY . /root
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories && apk add gcc && apk add g++ ccache nodejs &&  pip install -i https://mirrors.aliyun.com/pypi/simple/ -r /root/requirements.txt
WORKDIR /val
ENTRYPOINT ["sh", "/root/detect.sh"]
