FROM python:3.10.9-alpine3.17
COPY . /root
RUN pip install -r /root/requirements.txt && apk add --no-cache gcc g++ ccache nodejs && pip install ordered-set && pip install Nuitka
WORKDIR /val
ENTRYPOINT ["sh", "/root/detect.sh"]