FROM python:3.7.15-alpine3.17
COPY . /root
RUN apk add --update binutils openssh-client && pip3 install -i https://mirrors.aliyun.com/pypi/simple/ -r /root/requirements.txt
WORKDIR /val
ENTRYPOINT ["sh", "/root/detect.sh"]